/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.65
 * Generated at: 2024-01-14 07:04:37 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class EShop_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET, POST or HEAD. Jasper also permits OPTIONS");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write(" <meta http-equiv=\"Content-Type\" content=\"text/html; charset=UTF-8\">\r\n");
      out.write(" <title>Mode II 範例程式 - Eshop.jsp</title>\r\n");
      out.write("</head>\r\n");
      out.write("<body bgcolor=\"#FFFFFF\">\r\n");
      out.write("<img src=\"images/tomcat.gif\"> <font size=\"+3\">網路書店</font>\r\n");
      out.write("<hr><p>\r\n");
      out.write("\r\n");
      out.write("<table border=\"1\" width=\"740\">  \r\n");
      out.write("  <tr bgcolor=\"#999999\"> \r\n");
      out.write("    <th width=\"200\">書名</th><th width=\"100\">作者</th><th width=\"100\">出版社</th><th width=\"100\">價格</th>\r\n");
      out.write("    <th width=\"100\">數量</th><th width=\"120\"></th>\r\n");
      out.write("  </tr>\r\n");
      out.write("\r\n");
      out.write(" <!--  \r\n");
      out.write("       第一種action寫法: <form name=\"shoppingForm\" action=\"Shopping.html\" method=\"POST\">\r\n");
      out.write("       第二種action寫法: <form name=\"shoppingForm\" action=\"/IBM_MVC/Shopping.html\" method=\"POST\">\r\n");
      out.write("       第三種action寫法: <form name=\"shoppingForm\" action=\"");
      out.print(request.getContextPath());
      out.write("/Shopping.html\" method=\"POST\">\r\n");
      out.write(" -->\r\n");
      out.write(" <!-- \r\n");
      out.write("      當某網頁可能成為被forward的網頁時, 此網頁內的所有html連結 , 如果採用相對路徑寫法時, 因為會被加上原先forward者的路徑\r\n");
      out.write("      在更複雜的MVC架構中, 上面第三種寫法, 先以request.getContextPath()方法, 先取得環境(Servlet Context)目錄路徑的寫法,\r\n");
      out.write("      將是最佳解決方案\r\n");
      out.write(" -->\r\n");
      out.write("  \r\n");
      out.write("  <form name=\"shoppingForm\" action=\"Shopping.html\" method=\"POST\">\r\n");
      out.write("    <tr> \r\n");
      out.write("      <td width=\"200\"><div align=\"center\">不一樣的養生法</div></td>\r\n");
      out.write("      <td width=\"100\"><div align=\"center\">吳永志</div></td>\r\n");
      out.write("      <td width=\"100\"><div align=\"center\">基峰</div></td>\r\n");
      out.write("      <td width=\"100\"><div align=\"center\">600</div></td>\r\n");
      out.write("      <td width=\"120\"><div align=\"center\">數量： <input type=\"text\" name=\"quantity\" size=\"3\" value=1></div></td>\r\n");
      out.write("      <td width=\"120\"><div align=\"center\">      <input type=\"submit\" name=\"Submit\" value=\"放入購物車\"></div></td>\r\n");
      out.write("    </tr>\r\n");
      out.write("      <input type=\"hidden\" name=\"name\" value=\"不一樣的養生法\">\r\n");
      out.write("      <input type=\"hidden\" name=\"author\" value=\"吳永志\">\r\n");
      out.write("      <input type=\"hidden\" name=\"publisher\" value=\"基峰\">\r\n");
      out.write("      <input type=\"hidden\" name=\"price\" value=\"600\">\r\n");
      out.write("      <input type=\"hidden\" name=\"action\" value=\"ADD\">	\r\n");
      out.write("  </form>\r\n");
      out.write("  \r\n");
      out.write("  <form name=\"shoppingForm\" action=\"Shopping.html\" method=\"POST\">\r\n");
      out.write("    <tr> \r\n");
      out.write("      <td width=\"200\"><div align=\"center\">哈利波特-神秘的魔法石</div></td>\r\n");
      out.write("      <td width=\"100\"><div align=\"center\">J.K 羅琳</div></td>\r\n");
      out.write("      <td width=\"100\"><div align=\"center\">皇冠</div></td>\r\n");
      out.write("      <td width=\"100\"><div align=\"center\">200</div></td>\r\n");
      out.write("      <td width=\"120\"><div align=\"center\">數量： <input type=\"text\" name=\"quantity\" size=\"3\" value=1></div></td>\r\n");
      out.write("      <td width=\"120\"><div align=\"center\">      <input type=\"submit\" name=\"Submit\" value=\"放入購物車\"></div></td>\r\n");
      out.write("    </tr>\r\n");
      out.write("      <input type=\"hidden\" name=\"name\" value=\"哈利波特-神秘的魔法石\">\r\n");
      out.write("      <input type=\"hidden\" name=\"author\" value=\"J.K 羅琳\">\r\n");
      out.write("      <input type=\"hidden\" name=\"publisher\" value=\"皇冠\">\r\n");
      out.write("      <input type=\"hidden\" name=\"price\" value=\"200\">\r\n");
      out.write("      <input type=\"hidden\" name=\"action\" value=\"ADD\">\r\n");
      out.write("  </form>\r\n");
      out.write("  \r\n");
      out.write("  <form name=\"shoppingForm\" action=\"Shopping.html\" method=\"POST\">\r\n");
      out.write("    <tr> \r\n");
      out.write("      <td width=\"200\"><div align=\"center\">麻辣女教師</div></td>\r\n");
      out.write("      <td width=\"100\"><div align=\"center\">蕭蓉蓉</div></td>\r\n");
      out.write("      <td width=\"100\"><div align=\"center\">平安</div></td>\r\n");
      out.write("      <td width=\"100\"><div align=\"center\">190</div></td>\r\n");
      out.write("      <td width=\"120\"><div align=\"center\">數量： <input type=\"text\" name=\"quantity\" size=\"3\" value=1></div></td>\r\n");
      out.write("      <td width=\"120\"><div align=\"center\">      <input type=\"submit\" name=\"Submit\" value=\"放入購物車\"></div></td>\r\n");
      out.write("    </tr>\r\n");
      out.write("      <input type=\"hidden\" name=\"name\" value=\"麻辣女教師\">\r\n");
      out.write("      <input type=\"hidden\" name=\"author\" value=\"蕭蓉蓉\">\r\n");
      out.write("      <input type=\"hidden\" name=\"publisher\" value=\"平安\">\r\n");
      out.write("      <input type=\"hidden\" name=\"price\" value=\"190\">\r\n");
      out.write("      <input type=\"hidden\" name=\"action\" value=\"ADD\">\r\n");
      out.write("  </form>\r\n");
      out.write("  \r\n");
      out.write("  <form name=\"shoppingForm\" action=\"Shopping.html\" method=\"POST\">\r\n");
      out.write("    <tr> \r\n");
      out.write("      <td width=\"200\"><div align=\"center\">把話說到心窩裡</div></td>\r\n");
      out.write("      <td width=\"100\"><div align=\"center\">劉墉</div></td>\r\n");
      out.write("      <td width=\"100\"><div align=\"center\">水雲齋</div></td>\r\n");
      out.write("      <td width=\"100\"><div align=\"center\">180</div></td>\r\n");
      out.write("      <td width=\"120\"><div align=\"center\">數量： <input type=\"text\" name=\"quantity\" size=\"3\" value=1></div></td>\r\n");
      out.write("      <td width=\"120\"><div align=\"center\">      <input type=\"submit\" name=\"Submit\" value=\"放入購物車\"></div></td>\r\n");
      out.write("    </tr>\r\n");
      out.write("      <input type=\"hidden\" name=\"name\" value=\"把話說到心窩裡\">\r\n");
      out.write("      <input type=\"hidden\" name=\"author\" value=\"劉墉\">\r\n");
      out.write("      <input type=\"hidden\" name=\"publisher\" value=\"水雲齋\">\r\n");
      out.write("      <input type=\"hidden\" name=\"price\" value=\"180\">\r\n");
      out.write("      <input type=\"hidden\" name=\"action\" value=\"ADD\">\r\n");
      out.write("  </form>\r\n");
      out.write("  \r\n");
      out.write("  <form name=\"shoppingForm\" action=\"Shopping.html\" method=\"POST\">\r\n");
      out.write("    <tr> \r\n");
      out.write("      <td width=\"200\"><div align=\"center\">一個人聖經</div></td>\r\n");
      out.write("      <td width=\"100\"><div align=\"center\">高行健</div></td>\r\n");
      out.write("      <td width=\"100\"><div align=\"center\">聯經</div></td>\r\n");
      out.write("      <td width=\"100\"><div align=\"center\">300</div></td>\r\n");
      out.write("      <td width=\"120\"><div align=\"center\">數量： <input type=\"text\" name=\"quantity\" size=\"3\" value=1></div></td>\r\n");
      out.write("      <td width=\"120\"><div align=\"center\">      <input type=\"submit\" name=\"Submit\" value=\"放入購物車\"></div></td>\r\n");
      out.write("    </tr>\r\n");
      out.write("      <input type=\"hidden\" name=\"name\" value=\"一個人聖經\">\r\n");
      out.write("      <input type=\"hidden\" name=\"author\" value=\"高行健\">\r\n");
      out.write("      <input type=\"hidden\" name=\"publisher\" value=\"聯經\">\r\n");
      out.write("      <input type=\"hidden\" name=\"price\" value=\"300\">\r\n");
      out.write("      <input type=\"hidden\" name=\"action\" value=\"ADD\">\r\n");
      out.write("  </form>\r\n");
      out.write("\r\n");
      out.write("</table>\r\n");
      out.write("<p> \r\n");
      out.write("  ");
      org.apache.jasper.runtime.JspRuntimeLibrary.include(request, response, "/Cart.jsp", out, true);
      out.write("\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
