/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.65
 * Generated at: 2024-01-30 02:49:34 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.ad;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import com.ad.model.*;

public final class listOneAd_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("com.ad.model");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET, POST or HEAD. Jasper also permits OPTIONS");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");

// AdServlet 75~77行 setAttribute("adVO",adVO)後再forward到listOneEmp.jsp頁面取值
  AdVO adVO = (AdVO) request.getAttribute("adVO"); //adServlet.java(Concroller), 存入req的adVO物件

      out.write("\r\n");
      out.write("\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<title>員工資料 - listOneAd.jsp</title>\r\n");
      out.write("\r\n");
      out.write("<style>\r\n");
      out.write("  table#table-1 {\r\n");
      out.write("	background-color: #CCCCFF;\r\n");
      out.write("    border: 2px solid black;\r\n");
      out.write("    text-align: center;\r\n");
      out.write("  }\r\n");
      out.write("  table#table-1 h4 {\r\n");
      out.write("    color: red;\r\n");
      out.write("    display: block;\r\n");
      out.write("    margin-bottom: 1px;\r\n");
      out.write("  }\r\n");
      out.write("  h4 {\r\n");
      out.write("    color: blue;\r\n");
      out.write("    display: inline;\r\n");
      out.write("  }\r\n");
      out.write("</style>\r\n");
      out.write("\r\n");
      out.write("<style>\r\n");
      out.write("  table {\r\n");
      out.write("	width: 600px;\r\n");
      out.write("	background-color: white;\r\n");
      out.write("	margin-top: 5px;\r\n");
      out.write("	margin-bottom: 5px;\r\n");
      out.write("  }\r\n");
      out.write("  table, th, td {\r\n");
      out.write("    border: 1px solid #CCCCFF;\r\n");
      out.write("  }\r\n");
      out.write("  th, td {\r\n");
      out.write("    padding: 5px;\r\n");
      out.write("    text-align: center;\r\n");
      out.write("  }\r\n");
      out.write("</style>\r\n");
      out.write("\r\n");
      out.write("</head>\r\n");
      out.write("<body bgcolor='white'>\r\n");
      out.write("\r\n");
      out.write("<h4>此頁暫練習採用 Script 的寫法取值:</h4>\r\n");
      out.write("<table id=\"table-1\">\r\n");
      out.write("	<tr><td>\r\n");
      out.write("		 <h3>員工資料 - listOneEmp.jsp</h3>\r\n");
      out.write("		 <h4><a href=\"select_page.jsp\"><img src=\"images/back1.gif\" width=\"100\" height=\"32\" border=\"0\">回首頁</a></h4>\r\n");
      out.write("	</td></tr>\r\n");
      out.write("</table>\r\n");
      out.write("\r\n");
      out.write("<table>\r\n");
      out.write("	<tr>\r\n");
      out.write("		<th>廣告編號</th>\r\n");
      out.write("		<th>賣家ID</th>\r\n");
      out.write("		<th>廣告名稱</th>\r\n");
      out.write("		<th>廣告網址</th>\r\n");
      out.write("		<th>廣告開始時間</th>\r\n");
      out.write("		<th>廣告結束時間</th>\r\n");
      out.write("		<th>廣告等級</th>\r\n");
      out.write("		\r\n");
      out.write("	</tr>\r\n");
      out.write("	<tr>\r\n");
      out.write("		<td>");
      out.print(adVO.getAdId());
      out.write("</td>\r\n");
      out.write("		<td>");
      out.print(adVO.getSellerId());
      out.write("</td>\r\n");
      out.write("		<td>");
      out.print(adVO.getAdName());
      out.write("</td>\r\n");
      out.write("		<td>");
      out.print(adVO.getAdUrl());
      out.write("</td>\r\n");
      out.write("		<td>");
      out.print(adVO.getAdStartTime());
      out.write("</td>\r\n");
      out.write("		<td>");
      out.print(adVO. getAdEndTime());
      out.write("</td>\r\n");
      out.write("		<td>");
      out.print(adVO.getAdLv());
      out.write("</td>\r\n");
      out.write("	</tr>\r\n");
      out.write("</table>\r\n");
      out.write("\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
